name: Continuous Integration

on: pull_request

jobs:
  test:
    name: Run linter and tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

#      - run: npm ci
      - run: yarn install 
#      - run: npm run lint
      - run: yarn test
